### ISSUE TITLE
Simple Shredder

### ISSUE THREAD

**Issue by pedroalbanese** [lu4p/shred#3]
Hi, how to pass a filename or a wildcard as string? How to read a param passed via cmdline in Golang? I need a shredder that remove one or more files (./*.txt). Can you help-me please?

**Comment by luantak** [comment]
Look at the tests on how to pass a filename/ path: https://www.github.com/lu4p/shred/tree/master/shred_test.go

For wildcards I would suggest iterating over a https://pkg.go.dev/path/filepath#Glob

For reading arguments from the commandline use: 
https://pkg.go.dev/flag
https://gobyexample.com/command-line-flags

**Comment by pedroalbanese** [comment]
It deletes a single file, but I don't understand the wildcards part, how to pass asterisks?

```go
package main
import (
	"github.com/lu4p/shred"
    "flag"
)

func main() {

    var svar string
    flag.StringVar(&svar, "svar", "bar", "a string var")
    flag.Parse()
	shredconf := shred.Conf{Times: 33, Zeros: true, Remove: true}
	shredconf.Path(svar)
}
```

Edited by lu4p: (Please use code blocks)

**Comment by luantak** [comment]
```go
package main

import (
	"flag"
	"path/filepath"

	"github.com/lu4p/shred"
)

func main() {

	var svar string
	flag.StringVar(&svar, "svar", "bar", "a string var")
	flag.Parse()
	shredconf := shred.Conf{Times: 33, Zeros: true, Remove: true}
	matches, err := filepath.Glob(svar)
	if err != nil {
		panic(err)
	}

	for _, match := range matches {
		err := shredconf.Path(match)
		if err != nil {
			panic(err)
		}
	}
}

```

Something like this.

**Comment by pedroalbanese** [comment]
$ go build -ldflags=-s .
# github.com/lu4p/shred/corrupt
.\shred.go:20:9: match declared and not used
note: module requires Go 1.13

**Comment by luantak** [comment]
Sorry fixed now

**Comment by pedroalbanese** [comment]
Thank you very much!!

**Comment by luantak** [comment]
I rewrote the code a little, it was one of my first projects in go.
The old code had some potential bugs, when executing multiple shred functions at a time.
It should also be faster, because I simplified the code a little. 

To update run:
```
go get -u -v github.com/lu4p/shred
```

**Comment by pedroalbanese** [comment]
Hi again (sorry to return so soon). Is possible to set "iterations" and "remove" variables via flags?  

package main

import (
	"flag"
	"path/filepath"
	"github.com/lu4p/shred"
)



func main() {


	var del string
	var Times string
	var Remove string
	flag.StringVar(&del, "f", "", "input file, directory or wildcard.")
	flag.StringVar(&Times, "t", "", "N iterations.")
	flag.StringVar(&Remove, "r", "", "remove file.")
	flag.Parse()
	shredconf := shred.Conf{Times: "Times", Zeros: true, Remove: true}
	matches, err := filepath.Glob(del)
	if err != nil {
		panic(err)
	}

	for _, match := range matches {
		err := shredconf.Path(match)
		if err != nil {
			panic(err)
		}
	}
}

Thanks again.

**Comment by luantak** [comment]
Yes:

https://pkg.go.dev/flag#BoolVar
https://pkg.go.dev/flag#IntVar

**Comment by pedroalbanese** [comment]
Sorry, I'm not a programmer. I understand very little about programming languages. Could you give me an example of how to do it using my code? (I need a multiplatform shredder and I can compile go for all my devices .. but I don't understand anything about the language, sorry for the insistence)

**Comment by luantak** [comment]
Ok no worries, you would replace the lines above with this

```go
var Times int
flag.IntVar(&Times, "t", 1, "N iterations.")

var Remove bool
flag.BoolVar(&Remove, "r", false,  "Remove file afterwards.")
```
And the conf with this:
```go
shredconf := shred.Conf{Times: Times, Zeros: true, Remove: Remove}
```

**Comment by pedroalbanese** [comment]
.\main.go:26:27: cannot use "" (type string) as type bool in argument to flag.BoolVar
.\main.go:29:14: cannot use &Remove (type *int) as type *bool in argument to flag.BoolVar
.\main.go:34:26: cannot use Times (type bool) as type int in field value
.\main.go:34:53: cannot use Remove (type int) as type bool in field value

**Comment by luantak** [comment]
Does it work now?

**Comment by pedroalbanese** [comment]
The number of iterations is always 1

**Comment by pedroalbanese** [comment]
It worked, but the -r flag must contain a = sign..

**Comment by luantak** [comment]
How did you determine this, because when Times is set in the config its not?

**Comment by luantak** [comment]
`-r 2`

Should also work but idk

**Comment by pedroalbanese** [comment]
"-r 2" don't work, just "-r=true" "-r=false"

**Comment by luantak** [comment]
No sorry i thought it was about the iterations.

`-r` is enough, because the absence of -r is evaluated to false

**Comment by pedroalbanese** [comment]
Yeah, it's perfect! Thank You very much !!

**Comment by luantak** [comment]
Can you share your final program, then I can add something similar to this repo?

**Comment by pedroalbanese** [comment]
Like this? https://sourceforge.net/projects/go-shred/

**Comment by luantak** [comment]
No I meant the source code, just inline here is sufficent.

**Comment by pedroalbanese** [comment]
`package main

import (
	"flag"
	"path/filepath"
	"github.com/lu4p/shred"
)

func main() {


var Times int
flag.IntVar(&Times, "t", 13, "N iterations.")
var Remove bool
flag.BoolVar(&Remove, "r", false,  "remove file afterwards.")

	var del string
	flag.StringVar(&del, "f", "", "input file, directory or wildcard.")
	flag.Parse()
	shredconf := shred.Conf{Times: Times, Zeros: true, Remove: Remove}
	matches, err := filepath.Glob(del)
	if err != nil {
		panic(err)
	}

	for _, match := range matches {
		err := shredconf.Path(match)
		if err != nil {
			panic(err)

		}
	}
}`

**Comment by luantak** [comment]
Thanks

**Comment by pedroalbanese** [comment]
I thank you!

**Comment by pedroalbanese** [comment]
If you can, put the revised version of this code in a cmd folder, as a standard tool (I spent lot of time looking for a program like that to compile).

Thanks again!

**Comment by pedroalbanese** [comment]
Hello, I need your help. Do you have an email where I can contact you? 

Thanks in advance.

**Comment by luantak** [comment]
Yes look at my profile https://github.com/lu4p/

**Comment by pedroalbanese** [comment]
I sent you an email

**Comment by luantak** [comment]
I've already answered.
